In [206]:
import os
import sqlite3

conn = sqlite3.connect("superstore.db")
import pandas as pd

In [207]:
def run_query(query):
    return pd.read_sql_query(query, conn)

In [208]:
CSV_FILE = "Sample - Superstore.csv"
DB_FILE = "superstore.db"
OUTPUT_DIR = "outputs"
SQL_FILE = "sales_analysis.sql"

os.makedirs(OUTPUT_DIR, exist_ok=True)

In [209]:
df = pd.read_csv(CSV_FILE, encoding="latin1")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [210]:
df.shape

(9994, 21)

In [211]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [212]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

In [213]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [214]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub_category',
       'product_name', 'sales', 'quantity', 'discount', 'profit'],
      dtype='str')

In [215]:
df["order_date"] = pd.to_datetime(df["order_date"])
df["ship_date"] = pd.to_datetime(df["ship_date"])

df[["order_date", "ship_date"]].head()

  order_date  ship_date
0 2016-11-08 2016-11-11
1 2016-11-08 2016-11-11
2 2016-06-12 2016-06-16
3 2015-10-11 2015-10-18
4 2015-10-11 2015-10-18

In [216]:
conn = sqlite3.connect(DB_FILE)

In [217]:
df.to_sql("sales_data", conn, if_exists="replace", index=False)

print("Data loaded successfully into sales_data table.")

Data loaded successfully into sales_data table.

In [218]:
def run_query(query):
    return pd.read_sql_query(query, conn)

In [219]:
query = """
PRAGMA table_info(sales_data);
"""

run_query(query)

    cid           name       type  notnull dflt_value  pk
0     0         row_id    INTEGER        0       None   0
1     1       order_id       TEXT        0       None   0
2     2     order_date  TIMESTAMP        0       None   0
3     3      ship_date  TIMESTAMP        0       None   0
4     4      ship_mode       TEXT        0       None   0
5     5    customer_id       TEXT        0       None   0
6     6  customer_name       TEXT        0       None   0
7     7        segment       TEXT        0       None   0
8     8        country       TEXT        0       None   0
9     9           city       TEXT        0       None   0
10   10          state       TEXT        0       None   0
11   11    postal_code    INTEGER        0       None   0
12   12         region       TEXT        0       None   0
13   13     product_id       TEXT        0       None   0
14   14       category       TEXT        0       None   0
15   15   sub_category       TEXT        0       None   0
16   16   product_name       TEXT        0       None   0
17   17          sales       REAL        0       None   0
18   18       quantity    INTEGER        0       None   0
19   19       discount       REAL        0       None   0
20   20         profit       REAL        0       None   0

In [220]:
query = """
SELECT *
FROM sales_data
LIMIT 10;
"""

run_query(query)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,2016-11-08 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12 00:00:00,2016-06-16 00:00:00,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11 00:00:00,2015-10-18 00:00:00,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11 00:00:00,2015-10-18 00:00:00,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,2014-06-09 00:00:00,2014-06-14 00:00:00,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,2014-06-09 00:00:00,2014-06-14 00:00:00,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,8,CA-2014-115812,2014-06-09 00:00:00,2014-06-14 00:00:00,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,9,CA-2014-115812,2014-06-09 00:00:00,2014-06-14 00:00:00,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,10,CA-2014-115812,2014-06-09 00:00:00,2014-06-14 00:00:00,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

In [221]:
query = """
SELECT COUNT(*) AS total_rows
FROM sales_data;
"""

run_query(query)

   total_rows
0        9994

In [222]:
query = """
SELECT order_id, customer_name, region, sales, profit
FROM sales_data
WHERE region = 'West'
LIMIT 10;
"""

run_query(query)

         order_id    customer_name region     sales    profit
0  CA-2016-138688  Darrin Van Huff   West    14.620    6.8714
1  CA-2014-115812  Brosina Hoffman   West    48.860   14.1694
2  CA-2014-115812  Brosina Hoffman   West     7.280    1.9656
3  CA-2014-115812  Brosina Hoffman   West   907.152   90.7152
4  CA-2014-115812  Brosina Hoffman   West    18.504    5.7825
5  CA-2014-115812  Brosina Hoffman   West   114.900   34.4700
6  CA-2014-115812  Brosina Hoffman   West  1706.184   85.3092
7  CA-2014-115812  Brosina Hoffman   West   911.424   68.3568
8  CA-2016-161389     Irene Maddox   West   407.976  132.5922
9  CA-2014-167164  Alejandro Grove   West    55.500    9.9900

In [223]:
query = """
SELECT order_id, category, sub_category, sales, profit
FROM sales_data
WHERE category = 'Technology'
LIMIT 10;
"""

run_query(query)

         order_id    category sub_category     sales    profit
0  CA-2014-115812  Technology       Phones   907.152   90.7152
1  CA-2014-115812  Technology       Phones   911.424   68.3568
2  CA-2014-143336  Technology       Phones   213.480   16.0110
3  CA-2016-121755  Technology  Accessories    90.570   11.7741
4  CA-2016-117590  Technology       Phones  1097.544  123.4737
5  CA-2015-117415  Technology       Phones   371.168   41.7564
6  CA-2017-120999  Technology       Phones   147.168   16.5564
7  CA-2016-118255  Technology  Accessories    45.980   19.7714
8  CA-2016-169194  Technology  Accessories    45.000    4.9500
9  CA-2016-169194  Technology       Phones    21.800    6.1040

In [224]:
query = """
SELECT order_id, order_date, sales, profit
FROM sales_data
WHERE order_date >= '2017-01-01'
LIMIT 10;
"""

run_query(query)

         order_id           order_date    sales   profit
0  CA-2017-114412  2017-04-15 00:00:00   15.552   5.4432
1  US-2017-156909  2017-07-16 00:00:00   71.372  -1.0196
2  CA-2017-107727  2017-10-19 00:00:00   29.472   9.9468
3  CA-2017-120999  2017-09-10 00:00:00  147.168  16.5564
4  CA-2017-139619  2017-09-19 00:00:00   95.616   9.5616
5  CA-2017-114440  2017-09-14 00:00:00   19.050   8.7630
6  US-2017-118038  2017-12-09 00:00:00    1.248  -1.9344
7  US-2017-118038  2017-12-09 00:00:00    9.708  -5.8248
8  US-2017-118038  2017-12-09 00:00:00   27.240   2.7240
9  US-2017-119662  2017-11-13 00:00:00  230.376 -48.9549

In [225]:
query = """
SELECT order_id, customer_name, category, sales, profit
FROM sales_data
WHERE sales > 500
ORDER BY sales DESC
LIMIT 10;
"""

run_query(query)

         order_id       customer_name         category      sales     profit
0  CA-2014-145317         Sean Miller       Technology  22638.480 -1811.0784
1  CA-2016-118689        Tamara Chand       Technology  17499.950  8399.9760
2  CA-2017-140151        Raymond Buch       Technology  13999.960  6719.9808
3  CA-2017-127180        Tom Ashbrook       Technology  11199.968  3919.9888
4  CA-2017-166709        Hunter Lopez       Technology  10499.970  5039.9856
5  CA-2016-117121       Adrian Barton  Office Supplies   9892.740  4946.3700
6  CA-2014-116904        Sanjit Chand  Office Supplies   9449.950  4630.4755
7  US-2016-107440        Bill Shonely       Technology   9099.930  2365.9818
8  CA-2016-158841        Sanjit Engle       Technology   8749.950  2799.9840
9  CA-2016-143714  Christopher Conant       Technology   8399.976  1119.9968

In [226]:
query = """
SELECT order_id, region, category, sales, profit
FROM sales_data
WHERE region = 'East'
  AND category = 'Furniture'
  AND sales > 300
ORDER BY sales DESC
LIMIT 10;
"""

run_query(query)

         order_id region   category     sales     profit
0  CA-2017-118892   East  Furniture  4416.174  -630.8820
1  CA-2015-117086   East  Furniture  4404.900  1013.1270
2  US-2015-126977   East  Furniture  4228.704   158.5764
3  CA-2014-128209   East  Furniture  4007.840   -50.0980
4  CA-2014-116246   East  Furniture  3785.292   420.5880
5  US-2015-150630   East  Furniture  3083.430 -1665.0522
6  CA-2017-100111   East  Furniture  2888.127   609.7157
7  CA-2015-160227   East  Furniture  2621.322   553.3902
8  CA-2016-169670   East  Furniture  2563.056   313.2624
9  CA-2017-100111   East  Furniture  2254.410   375.7350

In [227]:
query = """
SELECT region,
       ROUND(SUM(sales), 2) AS total_sales
FROM sales_data
GROUP BY region
ORDER BY total_sales DESC;
"""

run_query(query)

    region  total_sales
0     West    725457.82
1     East    678781.24
2  Central    501239.89
3    South    391721.91

In [228]:
query = """
SELECT region,
       ROUND(SUM(profit), 2) AS total_profit
FROM sales_data
GROUP BY region
ORDER BY total_profit DESC;
"""

run_query(query)

    region  total_profit
0     West     108418.45
1     East      91522.78
2    South      46749.43
3  Central      39706.36

In [229]:
query = """
SELECT category,
       ROUND(SUM(sales), 2) AS total_sales,
       SUM(quantity) AS total_quantity
FROM sales_data
GROUP BY category
ORDER BY total_sales DESC;
"""

run_query(query)

          category  total_sales  total_quantity
0       Technology    836154.03            6939
1        Furniture    741999.80            8028
2  Office Supplies    719047.03           22906

In [230]:
query = """
SELECT category,
       ROUND(AVG(sales), 2) AS average_sales
FROM sales_data
GROUP BY category
ORDER BY average_sales DESC;
"""

run_query(query)

          category  average_sales
0       Technology         452.71
1        Furniture         349.83
2  Office Supplies         119.32

In [231]:
query = """
SELECT sub_category,
       ROUND(SUM(profit), 2) AS total_profit
FROM sales_data
GROUP BY sub_category
ORDER BY total_profit DESC;
"""

run_query(query)

   sub_category  total_profit
0       Copiers      55617.82
1        Phones      44515.73
2   Accessories      41936.64
3         Paper      34053.57
4       Binders      30221.76
5        Chairs      26590.17
6       Storage      21278.83
7    Appliances      18138.01
8   Furnishings      13059.14
9     Envelopes       6964.18
10          Art       6527.79
11       Labels       5546.25
12     Machines       3384.76
13    Fasteners        949.52
14     Supplies      -1189.10
15    Bookcases      -3472.56
16       Tables     -17725.48

In [232]:
query = """
SELECT product_name,
       ROUND(SUM(sales), 2) AS total_sales
FROM sales_data
GROUP BY product_name
ORDER BY total_sales DESC
LIMIT 10;
"""

run_query(query)

                                        product_name  total_sales
0              Canon imageCLASS 2200 Advanced Copier     61599.82
1  Fellowes PB500 Electric Punch Plastic Comb Bin...     27453.38
2  Cisco TelePresence System EX90 Videoconferenci...     22638.48
3       HON 5400 Series Task Chairs for Big and Tall     21870.58
4         GBC DocuBind TL300 Electric Binding System     19823.48
5   GBC Ibimaster 500 Manual ProClick Binding System     19024.50
6               Hewlett Packard LaserJet 3310 Copier     18839.69
7  HP Designjet T520 Inkjet Large Format Printer ...     18374.90
8          GBC DocuBind P400 Electric Binding System     17965.07
9        High Speed Automatic Electric Letter Opener     17030.31

In [233]:
query = """
SELECT product_name,
       ROUND(SUM(profit), 2) AS total_profit
FROM sales_data
GROUP BY product_name
ORDER BY total_profit DESC
LIMIT 10;
"""

run_query(query)

                                        product_name  total_profit
0              Canon imageCLASS 2200 Advanced Copier      25199.93
1  Fellowes PB500 Electric Punch Plastic Comb Bin...       7753.04
2               Hewlett Packard LaserJet 3310 Copier       6983.88
3                 Canon PC1060 Personal Laser Copier       4570.93
4  HP Designjet T520 Inkjet Large Format Printer ...       4094.98
5                  Ativa V4110MDD Micro-Cut Shredder       3772.95
6   3D Systems Cube Printer, 2nd Generation, Magenta       3717.97
7  Plantronics Savi W720 Multi-Device Wireless He...       3696.28
8               Ibico EPK-21 Electric Binding System       3345.28
9                  Zebra ZM400 Thermal Label Printer       3343.54

In [234]:
query = """
SELECT state,
       ROUND(SUM(sales), 2) AS total_sales
FROM sales_data
GROUP BY state
ORDER BY total_sales DESC
LIMIT 10;
"""

run_query(query)

          state  total_sales
0    California    457687.63
1      New York    310876.27
2         Texas    170188.05
3    Washington    138641.27
4  Pennsylvania    116511.91
5       Florida     89473.71
6      Illinois     80166.10
7          Ohio     78258.14
8      Michigan     76269.61
9      Virginia     70636.72

In [235]:
query = """
SELECT strftime('%Y-%m', order_date) AS month,
       ROUND(SUM(sales), 2) AS monthly_sales,
       ROUND(SUM(profit), 2) AS monthly_profit
FROM sales_data
GROUP BY month
ORDER BY month;
"""

run_query(query)

      month  monthly_sales  monthly_profit
0   2014-01       14236.90         2450.19
1   2014-02        4519.89          862.31
2   2014-03       55691.01          498.73
3   2014-04       28295.35         3488.84
4   2014-05       23648.29         2738.71
5   2014-06       34595.13         4976.52
6   2014-07       33946.39         -841.48
7   2014-08       27909.47         5318.11
8   2014-09       81777.35         8328.10
9   2014-10       31453.39         3448.26
10  2014-11       78628.72         9292.13
11  2014-12       69545.62         8983.57
12  2015-01       18174.08        -3281.01
13  2015-02       11951.41         2813.85
14  2015-03       38726.25         9732.10
15  2015-04       34195.21         4187.50
16  2015-05       30131.69         4667.87
17  2015-06       24797.29         3335.56
18  2015-07       28765.33         3288.65
19  2015-08       36898.33         5355.81
20  2015-09       64595.92         8209.16
21  2015-10       31404.92         2817.37
22  2015-11       75972.56        12474.79
23  2015-12       74919.52         8016.97
24  2016-01       18542.49         2824.82
25  2016-02       22978.82         5004.58
26  2016-03       51715.88         3611.97
27  2016-04       38750.04         2977.81
28  2016-05       56987.73         8662.15
29  2016-06       40344.53         4750.38
30  2016-07       39261.96         4432.88
31  2016-08       31115.37         2062.07
32  2016-09       73410.02         9328.66
33  2016-10       59687.75        16243.14
34  2016-11       79411.97         4011.41
35  2016-12       96999.04        17885.31
36  2017-01       43971.37         7140.44
37  2017-02       20301.13         1613.87
38  2017-03       58872.35        14751.89
39  2017-04       36521.54          933.29
40  2017-05       44261.11         6342.58
41  2017-06       52981.73         8223.34
42  2017-07       45264.42         6952.62
43  2017-08       63120.89         9040.96
44  2017-09       87866.65        10991.56
45  2017-10       77776.92         9275.28
46  2017-11      118447.83         9690.10
47  2017-12       83829.32         8483.35

In [236]:
query = """
SELECT strftime('%Y', order_date) AS year,
       ROUND(SUM(sales), 2) AS yearly_sales,
       ROUND(SUM(profit), 2) AS yearly_profit
FROM sales_data
GROUP BY year
ORDER BY year;
"""

run_query(query)

   year  yearly_sales  yearly_profit
0  2014     484247.50       49543.97
1  2015     470532.51       61618.60
2  2016     609205.60       81795.17
3  2017     733215.26       93439.27

In [237]:
query = """
SELECT customer_name,
       ROUND(SUM(sales), 2) AS total_sales
FROM sales_data
GROUP BY customer_name
ORDER BY total_sales DESC
LIMIT 10;
"""

run_query(query)

        customer_name  total_sales
0         Sean Miller     25043.05
1        Tamara Chand     19052.22
2        Raymond Buch     15117.34
3        Tom Ashbrook     14595.62
4       Adrian Barton     14473.57
5        Ken Lonsdale     14175.23
6        Sanjit Chand     14142.33
7        Hunter Lopez     12873.30
8        Sanjit Engle     12209.44
9  Christopher Conant     12129.07

In [238]:
query = """
SELECT customer_name,
       ROUND(SUM(profit), 2) AS total_profit
FROM sales_data
GROUP BY customer_name
ORDER BY total_profit DESC
LIMIT 10;
"""

run_query(query)

          customer_name  total_profit
0          Tamara Chand       8981.32
1          Raymond Buch       6976.10
2          Sanjit Chand       5757.41
3          Hunter Lopez       5622.43
4         Adrian Barton       5444.81
5          Tom Ashbrook       4703.79
6  Christopher Martinez       3899.89
7         Keith Dawkins       3038.63
8           Andy Reiter       2884.62
9         Daniel Raglin       2869.08

In [239]:
query = """
SELECT order_id,
       COUNT(*) AS duplicate_count
FROM sales_data
GROUP BY order_id
HAVING COUNT(*) > 1
ORDER BY duplicate_count DESC
LIMIT 10;
"""

run_query(query)

         order_id  duplicate_count
0  CA-2017-100111               14
1  CA-2017-157987               12
2  US-2016-108504               11
3  CA-2016-165330               11
4  US-2015-126977               10
5  CA-2016-105732               10
6  CA-2015-131338               10
7  US-2016-114013                9
8  US-2015-163433                9
9  CA-2017-140949                9

In [240]:
query = """
SELECT row_id,
       COUNT(*) AS duplicate_count
FROM sales_data
GROUP BY row_id
HAVING COUNT(*) > 1;
"""

run_query(query)

Empty DataFrame
Columns: [row_id, duplicate_count]
Index: []

In [241]:
query = """
SELECT product_name,
       ROUND(SUM(sales), 2) AS total_sales,
       ROUND(SUM(profit), 2) AS total_profit
FROM sales_data
GROUP BY product_name
HAVING total_profit < 0
ORDER BY total_profit ASC
LIMIT 10;
"""

run_query(query)

,product_name,total_sales,total_profit
0,Cubify CubeX 3D Printer Double Head Print,11099.96,-8879.97
1,Lexmark MX611dhe Monochrome Laser Printer,16829.90,-4589.97
2,Cubify CubeX 3D Printer Triple Head Print,7999.98,-3839.99
3,Chromcraft Bull-Nose Wood Oval Conference Tabl...,9917.64,-2876.12
4,Bush Advantage Collection Racetrack Conference...,9544.73,-1934.40
5,GBC DocuBind P400 Electric Binding System,17965.07,-1878.17
6,Cisco TelePresence System EX90 Videoconferenci...,22638.48,-1811.08
7,Martin Yale Chadless Opener Electric Letter Op...,16656.20,-1299.18
8,Balt Solid Wood Round Tables,6518.75,-1201.06
9,BoxOffice By Design Rectangular and Half-Moon ...,1706.25,-1148.44

In [242]:
query = """
SELECT
    SUM(CASE WHEN order_id IS NULL THEN 1 ELSE 0 END) AS missing_order_id,
    SUM(CASE WHEN order_date IS NULL THEN 1 ELSE 0 END) AS missing_order_date,
    SUM(CASE WHEN customer_name IS NULL THEN 1 ELSE 0 END) AS missing_customer_name,
    SUM(CASE WHEN sales IS NULL THEN 1 ELSE 0 END) AS missing_sales,
    SUM(CASE WHEN profit IS NULL THEN 1 ELSE 0 END) AS missing_profit
FROM sales_data;
"""

run_query(query)

,missing_order_id,missing_order_date,missing_customer_name,missing_sales,missing_profit
0,0,0,0,0,0

In [243]:
query = """
SELECT *
FROM sales_data
WHERE sales < 0;
"""

run_query(query)

Empty DataFrame
Columns: [row_id, order_id, order_date, ship_date, ship_mode, customer_id, customer_name, segment, country, city, state, postal_code, region, product_id, category, sub_category, product_name, sales, quantity, discount, profit]
Index: []

[0 rows x 21 columns]

In [244]:
query = """
SELECT *
FROM sales_data
WHERE quantity < 0;
"""

run_query(query)

Empty DataFrame
Columns: [row_id, order_id, order_date, ship_date, ship_mode, customer_id, customer_name, segment, country, city, state, postal_code, region, product_id, category, sub_category, product_name, sales, quantity, discount, profit]
Index: []

[0 rows x 21 columns]

In [245]:
query = """
SELECT MIN(order_date) AS first_order_date,
       MAX(order_date) AS last_order_date
FROM sales_data;
"""

run_query(query)

      first_order_date      last_order_date
0  2014-01-03 00:00:00  2017-12-30 00:00:00

In [246]:
all_queries = {
    "01_schema": """
    PRAGMA table_info(sales_data);
    """,

    "02_sample_data": """
    SELECT *
    FROM sales_data
    LIMIT 10;
    """,

    "03_total_rows": """
    SELECT COUNT(*) AS total_rows
    FROM sales_data;
    """,

    "04_filter_region_west": """
    SELECT order_id, customer_name, region, sales, profit
    FROM sales_data
    WHERE region = 'West'
    LIMIT 10;
    """,

    "05_filter_category_technology": """
    SELECT order_id, category, sub_category, sales, profit
    FROM sales_data
    WHERE category = 'Technology'
    LIMIT 10;
    """,

    "06_filter_date": """
    SELECT order_id, order_date, sales, profit
    FROM sales_data
    WHERE order_date >= '2017-01-01'
    LIMIT 10;
    """,

    "07_filter_sales_above_500": """
    SELECT order_id, customer_name, category, sales, profit
    FROM sales_data
    WHERE sales > 500
    ORDER BY sales DESC
    LIMIT 10;
    """,

    "08_multiple_filters": """
    SELECT order_id, region, category, sales, profit
    FROM sales_data
    WHERE region = 'East'
      AND category = 'Furniture'
      AND sales > 300
    ORDER BY sales DESC
    LIMIT 10;
    """,

    "09_sales_by_region": """
    SELECT region,
           ROUND(SUM(sales), 2) AS total_sales
    FROM sales_data
    GROUP BY region
    ORDER BY total_sales DESC;
    """,

    "10_profit_by_region": """
    SELECT region,
           ROUND(SUM(profit), 2) AS total_profit
    FROM sales_data
    GROUP BY region
    ORDER BY total_profit DESC;
    """,

    "11_sales_quantity_by_category": """
    SELECT category,
           ROUND(SUM(sales), 2) AS total_sales,
           SUM(quantity) AS total_quantity
    FROM sales_data
    GROUP BY category
    ORDER BY total_sales DESC;
    """,

    "12_average_sales_by_category": """
    SELECT category,
           ROUND(AVG(sales), 2) AS average_sales
    FROM sales_data
    GROUP BY category
    ORDER BY average_sales DESC;
    """,

    "13_profit_by_sub_category": """
    SELECT sub_category,
           ROUND(SUM(profit), 2) AS total_profit
    FROM sales_data
    GROUP BY sub_category
    ORDER BY total_profit DESC;
    """,

    "14_top_10_products_by_sales": """
    SELECT product_name,
           ROUND(SUM(sales), 2) AS total_sales
    FROM sales_data
    GROUP BY product_name
    ORDER BY total_sales DESC
    LIMIT 10;
    """,

    "15_top_10_products_by_profit": """
    SELECT product_name,
           ROUND(SUM(profit), 2) AS total_profit
    FROM sales_data
    GROUP BY product_name
    ORDER BY total_profit DESC
    LIMIT 10;
    """,

    "16_top_categories_by_sales": """
    SELECT category,
           ROUND(SUM(sales), 2) AS total_sales
    FROM sales_data
    GROUP BY category
    ORDER BY total_sales DESC;
    """,

    "17_top_states_by_sales": """
    SELECT state,
           ROUND(SUM(sales), 2) AS total_sales
    FROM sales_data
    GROUP BY state
    ORDER BY total_sales DESC
    LIMIT 10;
    """,

    "18_monthly_sales_trend": """
    SELECT strftime('%Y-%m', order_date) AS month,
           ROUND(SUM(sales), 2) AS monthly_sales,
           ROUND(SUM(profit), 2) AS monthly_profit
    FROM sales_data
    GROUP BY month
    ORDER BY month;
    """,

    "19_yearly_sales_trend": """
    SELECT strftime('%Y', order_date) AS year,
           ROUND(SUM(sales), 2) AS yearly_sales,
           ROUND(SUM(profit), 2) AS yearly_profit
    FROM sales_data
    GROUP BY year
    ORDER BY year;
    """,

    "20_top_customers_by_sales": """
    SELECT customer_name,
           ROUND(SUM(sales), 2) AS total_sales
    FROM sales_data
    GROUP BY customer_name
    ORDER BY total_sales DESC
    LIMIT 10;
    """,

    "21_top_customers_by_profit": """
    SELECT customer_name,
           ROUND(SUM(profit), 2) AS total_profit
    FROM sales_data
    GROUP BY customer_name
    ORDER BY total_profit DESC
    LIMIT 10;
    """,

    "22_duplicate_order_ids": """
    SELECT order_id,
           COUNT(*) AS duplicate_count
    FROM sales_data
    GROUP BY order_id
    HAVING COUNT(*) > 1
    ORDER BY duplicate_count DESC
    LIMIT 10;
    """,

    "23_duplicate_row_ids": """
    SELECT row_id,
           COUNT(*) AS duplicate_count
    FROM sales_data
    GROUP BY row_id
    HAVING COUNT(*) > 1;
    """,

    "24_loss_making_products": """
    SELECT product_name,
           ROUND(SUM(sales), 2) AS total_sales,
           ROUND(SUM(profit), 2) AS total_profit
    FROM sales_data
    GROUP BY product_name
    HAVING total_profit < 0
    ORDER BY total_profit ASC
    LIMIT 10;
    """,

    "25_missing_values_check": """
    SELECT
        SUM(CASE WHEN order_id IS NULL THEN 1 ELSE 0 END) AS missing_order_id,
        SUM(CASE WHEN order_date IS NULL THEN 1 ELSE 0 END) AS missing_order_date,
        SUM(CASE WHEN customer_name IS NULL THEN 1 ELSE 0 END) AS missing_customer_name,
        SUM(CASE WHEN sales IS NULL THEN 1 ELSE 0 END) AS missing_sales,
        SUM(CASE WHEN profit IS NULL THEN 1 ELSE 0 END) AS missing_profit
    FROM sales_data;
    """,

    "26_negative_sales_check": """
    SELECT *
    FROM sales_data
    WHERE sales < 0;
    """,

    "27_negative_quantity_check": """
    SELECT *
    FROM sales_data
    WHERE quantity < 0;
    """,

    "28_date_range_validation": """
    SELECT MIN(order_date) AS first_order_date,
           MAX(order_date) AS last_order_date
    FROM sales_data;
    """
}

print("all_queries dictionary created successfully.")

all_queries dictionary created successfully.

In [247]:
import os

OUTPUT_DIR = "outputs"
os.makedirs(OUTPUT_DIR, exist_ok=True)

combined_md = "# Superstore SQL Query Results\n\n"

for name, query in all_queries.items():
    result = run_query(query)

    csv_path = os.path.join(OUTPUT_DIR, f"{name}.csv")
    result.to_csv(csv_path, index=False)

    combined_md += f"## {name}\n\n"
    combined_md += result.head(20).to_string(index=False)
    combined_md += "\n\n"

with open(os.path.join(OUTPUT_DIR, "query_results.md"), "w", encoding="utf-8") as f:
    f.write(combined_md)

print("outputs folder created and query results saved successfully.")

outputs folder created and query results saved successfully.